/** @type {import('tailwindcss').Config} */

export default {
    content: [
        './index.html',
        './src/**/*.{js,ts,jsx,tsx}',
        './.storybook/**/*.ts',
    ],
    future: {
        hoverOnlyWhenSupported: true,
    },
    theme: {
        extend: {
            colors: {
                'color-info': '#A0AEC0',
                'color-border': '#E2E8F0',
                'color-grey800': '#2D3748',
                'color-grey600': '#718096',
                'color-grey500': '#A0AEC0',
                'color-grey400': '#CBD5E0',
                'color-grey200': '#EDF2F7',
                'color-accent': '#0066FF',
                'color-secondary': '#DEEBFC',
                'color-halfaccent': '#3385FF',
                'color-success': '#66CB9F',
                'color-error': '#F16063',
                'color-third': '#A8CBEE',
                'color-warning': '#FFD363',
                'color-press-secondary': '#76ACFB',
            },
            fontFamily: {
                openSans: ['OpenSans'],
                inter: ['Inter'],
                raleway: ['Raleway'],
            },
            boxShadow: {
                sm: '0px 3px 8px -1px rgba(50, 50, 71, 0.05),0px 0px 1px 0px rgba(12, 26, 75, 0.24)',
            },
            borderWidth: {
                1: '1px',
                2: '2px',
                3: '3px',
                4: '4px',
            },
            borderRadius: {
                none: '0px',
                sm: '2px',
                DEFAULT: '4px',
                md: '6px',
                lg: '8px',
                xl: '12px',
                '2xl': '16px',
                '3xl': '24px',
                full: '50%',
            },
            spacing: {
                px: '1px',
                0: '0',
                0.5: '2px',
                1: '4px',
                1.5: '6px',
                2: '8px',
                2.5: '10px',
                3: '12px',
                3.5: '14px',
                4: '16px',
                4.5: '18px',
                5: '20px',
                5.5: '22px',
                6: '24px',
                6.5: '26px',
                7: '28px',
                7.5: '30px',
                8: '32px',
                8.5: '34px',
                9: '36px',
                10: '40px',
                11: '44px',
                12: '48px',
                12.5: '50px',
                14: '56px',
                15: '60px',
                16: '64px',
                17: '68px',
                18: '72px',
                20: '80px',
                22.5: '90px',
                24: '96px',
            },
            lineHeight: {
                none: '1',
                tight: '1.25',
                snug: '1.375',
                normal: '1.5',
                relaxed: '1.625',
                loose: '2',
                3: '12px',
                3.5: '14px',
                4: '16px',
                4.5: '18px',
                5: '20px',
                6: '24px',
                7: '28px',
                8: '32px',
                9: '36px',
                10: '40px',
            },
            fontSize: {
                s1: '36px',
                s2: '32px',
                s3: '24px',
                s4: '18px',
                s5: '16px',
                s6: '14px',
                s7: '12px',
                s8: '10px',
                xxs: ['10px', { lineHeight: 'normal' }],
                xs: ['12px', { lineHeight: '15px' }],
                sm: ['14px', { lineHeight: '20px' }],
                base: ['16px', { lineHeight: '18px' }],
                lg: ['18px', { lineHeight: '28px' }],
                xl: ['20px', { lineHeight: '28px' }],
                '2xl': ['24px', { lineHeight: '32px' }],
                '3xl': ['30px', { lineHeight: '36px' }],
                '4xl': ['36px', { lineHeight: '36px' }],
                '5xl': ['48px', { lineHeight: '1' }],
                '6xl': ['60px', { lineHeight: '1' }],
                '7xl': ['72px', { lineHeight: '1' }],
                '8xl': ['96px', { lineHeight: '1' }],
                '9xl': ['144px', { lineHeight: '1' }],
            },
        },
    },
}
